
mkdir data
cd data
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/144.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Buss/12month1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Priebel/192bit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Priebel/208bit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Um/2cubes_sphere.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/2D_27628_bjtcai.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/2D_54019_highK.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/333SP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/3D_28984_Tetra.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/3D_51448_3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sinclair/3Dspectralwave.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sinclair/3Dspectralwave2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rothberg/3dtube.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/598a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/a0nsdsil.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/a2nnsnsl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/a5esindl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Puri/ABACUS_shell_hd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Puri/ABACUS_shell_ld.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Puri/ABACUS_shell_md.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Puri/ABACUS_shell_ud.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/adaptive.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_0_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_1_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_2_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_3_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_4_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_5_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_AFE/af_shell9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bai/af23560.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Engwirda/airfoil_2d.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ak2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/al2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/amazon0302.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/amazon0312.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/amazon0505.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/amazon0601.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/amazon-2008.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrews/Andrews.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/apache1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/apache2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/appu.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ar2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/AS365.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/as-caida.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_100k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_100ks.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_320k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_320ks.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_680k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/ASIC_680ks.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/as-Skitter.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Newman/astro-ph.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bourchtein/atmosmodd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bourchtein/atmosmodj.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bourchtein/atmosmodl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bourchtein/atmosmodm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/audikw_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/aug3dcqp.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/auto.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Vavasis/av41092.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/az2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/barrier2-9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Watson/Baumann.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rommes/bauru5727.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/baxter.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Grund/bayer01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Grund/bayer04.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/bbmat.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamm/bcircuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk25.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk29.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HB/bcsstk32.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/bcsstk35.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/bcsstk36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/bcsstk37.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/bcsstk39.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/bcsstm36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/belgium_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/BenElechi/BenElechi1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/bfly.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/blockqp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/bloweya.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/bloweybl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/bmw3_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/bmw7st_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/bmwcra_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/bodyy4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/bodyy5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/bodyy6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/bone010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/boneS01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/boneS10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/boyd1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/boyd2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/brack2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/brainpc2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/bratu3d.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Bump_2911.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mazaheri/bundle_adj.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Lourakis/bundle1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-42.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-43.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-45.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-46.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-47.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-48.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-49.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-51.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-52.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-53.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-54.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-55.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-56.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-57.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-58.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-59.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-60.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-61.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-62.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-62ghs.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-63.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-64.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-64b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-65.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-66.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-66b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-67.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-67b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-68.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-69.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-70.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-71.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/c-72.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-73.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-73b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ca2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/ca-AstroPh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/ca-CondMat.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanHeukelum/cage15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/ca-HepPh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/caidaRouterLevel.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/cant.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QY/case39.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QY/case9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Margulies/cat_ears_4_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMNA/c-big.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/cbuckle.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/cca.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/ccc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rothberg/cfd1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rothberg/cfd2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-7-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-8-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-8-b4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-8-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-9-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-9-b4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch7-9-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch8-8-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch8-8-b4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/ch8-8-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/channel-500x100x100-b050.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Muite/Chebyshev4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Watson/chem_master1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chevron/Chevron1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chevron/Chevron2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chevron/Chevron3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chevron/Chevron4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/chipcool0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/chipcool1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bomhof/circuit_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/circuit5M.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/circuit5M_dc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/citationCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/cit-HepPh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/cit-HepTh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/cit-Patents.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/ckt11752_dc_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/ckt11752_tr_0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/cnr-2000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/CO.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/co2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/co9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/coAuthorsCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/coAuthorsDBLP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Newman/cond-mat-2003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Newman/cond-mat-2005.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf5_4-8x8-05.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf5_4-8x8-10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf5_4-8x8-15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf5_4-8x8-20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf6_0-8x8-20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf6_0-8x8-30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QCD/conf6_0-8x8-80.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/consph.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/cont1_l.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/cont11_l.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/cont-201.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/cont-300.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/cop20k_A.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/coPapersCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/coPapersDBLP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/copter1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/copter2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/CoupCons3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/crankseg_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/crankseg_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QLi/crashbasis.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/crplat2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/crystk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/crystk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/crystm02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/crystm03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ct2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/ct20stif.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Cube_Coup_dt0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Cube_Coup_dt6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bodendiek/CurlCurl_0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bodendiek/CurlCurl_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bodendiek/CurlCurl_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bodendiek/CurlCurl_3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bodendiek/CurlCurl_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/cvxbqp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/cvxqp3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/cyl6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CPM/cz10228.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CPM/cz20468.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CPM/cz40948.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/d_pretok.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/D6-6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/darcy003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/dawson5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/dbic1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/dbir1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/dbir2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/dblp-2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/dc1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/dc2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/dc3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/de2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/debr.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/degme.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/delaunay_n22.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ANSYS/Delor295K.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ANSYS/Delor338K.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ANSYS/Delor64K.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Toledo/deltaX.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Castrillon/denormal.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/dictionary28.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dziekonski/dielFilterV2clx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dziekonski/dielFilterV2real.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dziekonski/dielFilterV3clx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dziekonski/dielFilterV3real.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/dixmaanl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/UTEP/Dubcova1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/UTEP/Dubcova2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/UTEP/Dubcova3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/e18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Shen/e40r0100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/EAT_RS.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/EAT_SR.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sanghavi/ecl32.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/McRae/ecology1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/McRae/ecology2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/email-Enron.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/email-EuAll.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Emilia_923.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/engine.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/enron.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Averous/epb2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Averous/epb3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Springer/ESOC.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dattorro/EternityII_E.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dattorro/EternityII_Etilde.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/eu-2005.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FIDAP/ex11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FIDAP/ex19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FIDAP/ex35.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Koutsovasilis/F1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Koutsovasilis/F2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Fault_639.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/fcondp2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/fe_body.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/fe_ocean.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/fe_rotor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/fe_tooth.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/FEM_3D_thermal1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/FEM_3D_thermal2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Lee/fem_filter.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Lee/fem_hifreq_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/filter3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mulvey/finan512.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/finance256.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/fl2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Flan_1565.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/flickr.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Margulies/flower_7_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Margulies/flower_8_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/foldoc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/fome12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/fome13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/fome20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/fome21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/ford1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/ford2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Franz/Franz11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/Freescale1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/Freescale2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/fullb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/FullChip.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/fxm3_16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/fxm4_6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/G_n_pin_pout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AMD/G2_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AMD/G3_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac040.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac040sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac050sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac060.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac060sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac080.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac080sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac100sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac120sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac140.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac140sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac160.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac160sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac180.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac180sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac200.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/g7jac200sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ga10As10H30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ga19As19H42.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ga2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ga3As3H12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ga41As41H72.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/GaAsH6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Garon/garon2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/gas_sensor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ge87H76.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Ge99H100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rothberg/gearbox.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Geo_1438.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d22.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d23.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_GL7d/GL7d24.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sumner/graphics.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/great-britain_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/gridgena.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dziekonski/gsm_106857.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gupta/gupta1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gupta/gupta2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gupta/gupta3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/gyro.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/gyro_k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/gyro_m.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/H2O.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/halfb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamrle/Hamrle3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/hangGlider_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/hangGlider_5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamm/hcircuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/helm2d03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/helm3d01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/HEP-th-new.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/hi2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/hollywood-2009.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/hood.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Hook_1498.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IPSO/HTC_336_4438.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IPSO/HTC_336_9129.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/hugetrace-00000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/hugetric-00000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/hugetric-00010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/hugetric-00020.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Belcastro/human_gene1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Belcastro/human_gene2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Fluorem/HV15R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HVDC/hvdc1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HVDC/hvdc2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ia2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/ibm_matrix_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meng/iChem_Jacobian.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/id2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_G5/IG5-15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_G5/IG5-16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_G5/IG5-17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_G5/IG5-18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/igbt3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/il2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Szczerba/Ill_Stokes.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Yoshiyasu/image_interp.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/IMDB.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/in-2004.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/in2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/inlet.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/inline_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/ins2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/internet.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/POLYFLOW/invextr1_new.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/italy_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac060.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac060sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac080.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac080sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac100sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/jan99jac120sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/jnlbrng1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Harvard_Seismology/JP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rommes/juba40k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/k1_san.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cunningham/k3plates.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/karted.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Kim/kim1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Kim/kim2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zaoui/kkt_power.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Margulies/kneser_10_4_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/kron_g500-logn21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ks2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ky2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/la2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Raju/laminar_duct3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Tromble/language.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QLi/largebasis.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Stevenson/LargeRegFile.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/ldoor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LeGresley/LeGresley_87936.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr10c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr11c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr14c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr17c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr34.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr34c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr71.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mallya/lhr71c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Li/li.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dehghani/light_in_tissue.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Lin/Lin.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sorensen/Linux_call_graph.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LAW/ljournal-2008.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Long_Coup_dt0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Long_Coup_dt6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VDOL/lowThrust_9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LPnetlib/lp_ken_18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Qaplib/lp_nug20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Qaplib/lp_nug30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LPnetlib/lp_osa_60.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LPnetlib/lp_pds_10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/LPnetlib/lp_pds_20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/lp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/lpl1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/lpl3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Norris/lung2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/luxembourg_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/m_t1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/m133-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/m14b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/M6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ma2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/mac_econ_fwd500.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/QLi/majorbasis.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NYPA/Maragal_6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NYPA/Maragal_7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NYPA/Maragal_8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/mario001.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/mario002.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac040.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac040sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac060.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac060sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac080.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac080sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac100sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac120sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac140.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hollinger/mark3jac140sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/matrix_9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_IBMSDS/matrix-new_3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/mc2depi.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/md2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/me2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/memchip.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamm/memplus.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/mi2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/minsurfo.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/mip1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/POLYFLOW/mixtank_new.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/mk12-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/mk12-b4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/mk13-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/ML_Geer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/ML_Laplace.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/mn2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/mo2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/mod2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FreeFieldTechnologies/mono_500Hz.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Belcastro/mouse_gene.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bydder/mri1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bydder/mri2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ms2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/msc10848.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/msc23052.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/INPRO/msdoor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/mt2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/mult_dcop_01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/mult_dcop_02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Sandia/mult_dcop_03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/n4c6-b9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/NACA0015.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Nasa/nasasrb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nc2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/ncvxbqp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/ncvxqp3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/ncvxqp5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/ncvxqp7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ND/nd12k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nd2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ND/nd24k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ND/nd6k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ne2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/neos.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/neos1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/neos2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/neos3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net125.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net150.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net4-1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/net75.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/netherlands_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nh2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nj2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk/nlpkkt120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk/nlpkkt80.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/NLR.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nm2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/nmos3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Barabasi/NotreDame_actors.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Barabasi/NotreDame_www.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/ns3Da.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/nsct.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/nug08-3rd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/nv2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ny2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/obstclae.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Um/offshore.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/oh2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/ohne2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/oilpan.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ok2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/olafu.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/olesnik0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/onera_dual.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ATandT/onetone1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ATandT/onetone2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IPSO/OPF_10000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IPSO/OPF_3754.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IPSO/OPF_6000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/opt1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/or2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/p010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/p2p-Gnutella31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/pa2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/packing-500x100x100-b050.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schenk_ISEI/para-9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Wissgott/parabolic_fem.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/patents.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/patents_main.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrianov/pattern1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/pcrystk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/pcrystk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/pct20stif.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/pdb1HYS.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/pds10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-40.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-60.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-70.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-80.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/pds-90.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mulvey/pfinan512.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/PFlow_742.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk04.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk05.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk06.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk07.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk08.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk09.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chen/pkustk14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Li/pli.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/pltexpa.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/poisson3Da.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/poisson3Db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Fluorem/PR02R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ATandT/pre2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/preferentialAttachment.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ACUSIM/Pres_Poisson.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/YCheng/psse0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/YCheng/psse2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Nasa/pwt.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Boeing/pwtk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cunningham/qa8fk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cunningham/qa8fm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/raefsky3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/raefsky4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/rail_20209.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/rail_79841.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/Raj1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat09.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat22.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat23.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat24.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat25.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat26.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat28.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat29.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rajat/rajat31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/ramage02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Relat/rel8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Relat/rel9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Relat/relat8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Relat/relat9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/Reuters911.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rost/RFdevice.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_15_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_16_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_17_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_18_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_19_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_20_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_21_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/rgg_n_2_22_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ri2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Goodwin/rim.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/rlfprim.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Fluorem/RM07R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bova/rma10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/roadNet-CA.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/roadNet-PA.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/roadNet-TX.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/route.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rucci/Rucci1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/s3dkq4m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/s3dkt3m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/s4dkt3m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/sc2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/sc205-2r.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/scagr7-2r.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/scfxm1-2b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/scfxm1-2r.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamm/scircuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/sctap1-2r.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/sd2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Serena.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/sgpf5y6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/MaxPlanck/shallow_water1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/MaxPlanck/shallow_water2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/shar_te2-b2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Homology/shar_te2-b3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Shen/shermanACb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/ship_001.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/ship_003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/shipsec1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/shipsec5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/shipsec8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/shock-9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Nasa/shuttle_eddy.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Shyy/shyy161.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Si10H16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Si34H36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Si41Ge41H72.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Si5H12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/Si87H76.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hohn/sinc15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hohn/sinc18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/SiO.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PARSEC/SiO2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Nasa/skirt.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bates/sls.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/smallworld.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/sme3Da.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/sme3Db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/sme3Dc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/smt.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-Epinions1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-LiveJournal1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-sign-epinions.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-sign-Slashdot081106.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-sign-Slashdot090216.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-sign-Slashdot090221.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-Slashdot0811.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/soc-Slashdot0902.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/south31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/spal_004.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/sparsine.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/spmsrtls.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/srb1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Kamvar/Stanford.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Kamvar/Stanford_Berkeley.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/stat96v2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/stat96v3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/std1_Jac2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/std1_Jac2_db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/std1_Jac3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/std1_Jac3_db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/StocF-1465.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/stokes128.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/stokes64.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/stokes64s.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Norris/stomach.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/stormG2_1000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/stormg2-125.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rothberg/struct3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t2dah.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t2dah_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t2dah_e.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CEMW/t2em.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t3dh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t3dh_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t3dh_e.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t3dl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/t3dl_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/t60k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/tandem_dual.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pothen/tandem_vtx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_A.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_A_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_AB.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_AB_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_B.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bindel/ted_B_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Forest/TF16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Forest/TF17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Forest/TF18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Forest/TF19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schmid/thermal1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Schmid/thermal2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/thermomech_dK.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/thermomech_dM.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/thermomech_TC.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Botonakis/thermomech_TK.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/thread.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CEMW/tmt_sym.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CEMW/tmt_unsym.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/tn2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Clark/tomographic1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/torsion1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Norris/torso1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Norris/torso2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Norris/torso3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/tp-6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/trans4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/IBM_EDA/trans5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale/transient.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Janna/Transport.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/trdheim.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Trefethen/Trefethen_20000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Trefethen/Trefethen_20000b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/troll.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b162_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b162_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b162_c4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b300.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b300_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b300_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b300_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b39_c19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b39_c30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b39_c7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_FS_b9_c6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b162_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b162_c4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b2052_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b2383.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b2383_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b300_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b300_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b300_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b39_c19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b39_c30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b39_c7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b678_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF/TSOPF_RS_b678_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/ts-palko.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/tsyl201.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/tube1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TKK/tube2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_indef/turon_m.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ATandT/twotone.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/tx2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/usroads.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/usroads-48.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/ut2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/va2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/vanbody.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/venkat01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/venkat25.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Simon/venkat50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/venturiLevel3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CEMW/vfem.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cote/vibrobox.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Quaglino/viscoplastic2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mancktelow/viscorocks.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_barth5_1Ksep_50in_5Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_bcsstk30_500sep_10in_1Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_befref_fxm_2_4_air02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_bump2_e18_aa01_model1_crew1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_c-30_data_data.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_c-60_data_cti_cs4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_finan512_scagr7-2c_rlfddd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_mod2_pgp2_slptsk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_model1_crew1_cr42_south31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_msc10848_300sep_100in_1Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_p0291_seymourl_iiasa.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_sctap1-2b_and_seymourl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_south31_slptsk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vsp_vibrobox_scagr7-2c_rlfddd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/vt2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wa2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Wang/wang3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Wang/wang4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Rudnyi/water_tank.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/wathen100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GHS_psdef/wathen120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/watson_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Mittelmann/watson_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AG-Monien/wave.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FEMLAB/waveguide3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Williams/webbase-1M.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/web-BerkStan.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/web-Google.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/web-NotreDame.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/web-Stanford.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/JGD_Margulies/wheel_601.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wi2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/wikipedia-20051105.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/wikipedia-20060925.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/wikipedia-20061104.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Gleich/wikipedia-20070206.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SNAP/wiki-Talk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Oberwolfach/windscreen.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wing.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wing_nodal.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pajek/Wordnet3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Meszaros/world.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wv2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DIMACS10/wy2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/DNVS/x104.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ronis/xenon1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ronis/xenon2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac2_db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac3_db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/VanVelzen/Zd_Jac6_db.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zhao/Zhao1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zhao/Zhao2.tar.gz
find . -name '*.tar.gz' -exec tar xvf {} \;
rm *.tar.gz
cp ../conv.c .
gcc -O3 -o conv conv.c

for i in `ls -d */`
do
cd ${i}
ii=`echo ${i} | sed -e "s/\///g"`
mv ${ii}.mtx ${ii}.mt0
../conv ${ii}.mt0 ${ii}.mtx 
rm ${ii}.mt0
cd ..
done

cd ..

